smtpInfo:
    smtp_host: mail.tmax.co.kr
    smtp_port: 587
    smtp_id: jinsoo_youn@tmax.co.kr
    smtp_pw: wlstn1212
message:
    from: jinsoo_youn@tmax.co.kr
    to: ['jinsoo_youn@tmax.co.kr','yjs890403@gmail.com']
    subject: golang mail test
    body: this email built in golang 