smtpInfo:
    smtp_host: mail.tmax.co.kr
    smtp_port: 587
    smtp_id: jinsoo_youn@tmax.co.kr
    smtp_pw: wlstn1212
message:
    from: jinsoo_youn@tmax.co.kr
    to: ['jinsoo_youn@tmax.co.kr']
    subject: "[@@PRODUCT@@] Release Update - @@PRODUCT@@:@@MAJOR_VERSION@@.@@MINOR_VERSION@@.@@PATCH_VERSION@@.@@HOTFIX_VERSION@@"
    body: |
        안녕하세요.

        @@PRODUCT@@ Release Update 입니다.

        변경사항 파일로 첨부합니다.

        감사합니다.


        * IP Range Validation을 테스트하기 위해 다음이 보장되어야 합니다. (가이드 참고)
        - Load Balancer 서비스로 생성하여야 합니다.
        - Load Balancer Service 생성을 위한 yaml 파일의 spec에 "externalTrafficPolicy: Local" 이 추가되어야 합니다.
        - Deployment 생성을 위한 yaml 파일의 template > spec에 "serviceAccountName: (적절한 namespace admin)"이 추가되어야 합니다.
        - UI 접속 시 LoadBalancer Public IP를 사용해야 합니다.

        * HDC 모드로 설치하는 경우 로그인 정상동작을 위해 다음을 주의하여야 합니다.
        - HDC (public) 모드로 설치하는 경우에는 console과 portal이 쿠키를 공유할 수 있도록 같은 도메인의 서브도메인으로 세팅되어야 합니다.
        - console과 portal 둘 다 443 포트의 LB 서비스로 생성하거나, 또는 둘 다 Node Port 서비스로 생성하고서 둘 다 동일한 Node IP로만 접속해야 합니다.
        (Node Port를 사용하는 경우, 로그인용 계정에 UserSecurityPolicy가 설정되어 있으면 IP Range Validation에서 오동작을 할 수 있습니다.)


        ※ 이미지 : @@DOCKER_REGISTRY@@/@@PRODUCT@@:${MAJOR_VERSION}.@@MINOR_VERSION@@.@@PATCH_VERSION@@.@@HOTFIX_VERSION@@

        ※ 설치 가이드 : @@GUIDE_URL@@
    attach: './static/config/[HOTFIX]CHANGELOG.md'